# -*- coding: utf-8 -*-
"""stable-diffusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNwv5DlWNdMJ0QiIXfL36p7syJiyCcmk

# Stable Diffusion

```{note}
Install ekorpkit package first.

Set logging level to Warning, if you don't want to see verbose logging.

If you run this notebook in Colab, set Hardware accelerator to GPU.
```

```python
%pip install -U --pre ekorpkit[art]

exit()
```
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U --pre ekorpkit[art]

"""## Prepare Environment"""

from ekorpkit import eKonf

eKonf.setLogger("WARNING")
print("version:", eKonf.__version__)

is_colab = eKonf.is_colab()
print("is colab?", is_colab)
if is_colab:
    eKonf.mount_google_drive()
workspace_dir = "/MyDrive/workspace"
project_name = "ekorpkit-book"
ws = eKonf.set_workspace(workspace=workspace_dir, project=project_name)
print("project_dir:", ws.project_dir)
ws.envs.dict()

"""## Create a stable diffusion instance

To download a certain dataset or model checkpoint, you may need to provide a HuggingFace API token. You can get one from [here](https://huggingface.co/settings/token).

```python
# Set HuggingFace API token
ws.secrets.HUGGING_FACE_HUB_TOKEN = "YOUR_TOKEN"
```
"""

# Set HuggingFace API token
ws.secrets.HUGGING_FACE_HUB_TOKEN = "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"

ws.secrets.dict()

# Set CUDA DEVICES for the model

ws.envs.CUDA_VISIBLE_DEVICES = "0"

from ekorpkit.tasks.multi import StableDiffusion

sd = StableDiffusion()

"""## Generate images"""

text_prompts = "people looking out the lonely city street from windows of buildings in a Edward Hopper style. detailed, romantic, enchanting, trending on artstation."
batch_name = "hopper-street"
sd.config.collage.ncols = 2
sd.config.batch.verbose = True

results = sd.generate(
    text_prompts, 
    batch_name=batch_name, 
    num_samples=4, 
    guidance_scale=9,
    width=800,
    height=400,
    num_inference_steps=50,
)

base_url = "https://github.com/entelecheia/ekorpkit-book/raw/main/assets/figs"
init_image_path = f"{base_url}/chu-horse.png"
batch_name = "horse-init"
text_prompts = "a golden statue of an eagle with clouds"
sd.config.collage.ncols = 2

results = sd.generate(
    text_prompts, 
    batch_name=batch_name, 
    init_image=init_image_path,
    num_samples=4, 
    guidance_scale=30,
    width=800,
    height=400,
    num_inference_steps=50,
)